version: '3'

vars:
  OUT_DIR: out

tasks:
  bench:
    cmds:
      - rm -rf out && mkdir out
      - go test -bench=. -count=3 -benchtime=5s -benchmem -cpuprofile={{ .OUT_DIR }}/cpu.prof -memprofile={{ .OUT_DIR }}/mem.prof | tee out/result.txt

  proto:
    cmds:
      - task: proto-v2
      - task: proto-v2vtproto
      - task: proto-v2gogo

  proto-v2:
    cmds:
      - protoc -I=. --go_out=. proto/V2/*.proto

  proto-v2vtproto:
    cmds:
      - protoc -I=. --go_out=. --go-vtproto_out=. proto/V2vtproto/*.proto

  proto-v2gogo:
    cmds:
      - protoc -I=. --gofast_out=. proto/V2gogo/*.proto
