version: '3'

vars:
  OUT_DIR: out

tasks:
  bench:
    cmds:
      - rm -rf out && mkdir out
      - go test -bench=. -count=6 -benchtime=5s -benchmem -cpuprofile={{ .OUT_DIR }}/cpu.prof -memprofile={{ .OUT_DIR }}/mem.prof
